   ID DIVISION.
       PROGRAM-ID. HELLO.

      *    THIS IS A program
      *
      *    THIS PROGRAM WILL RECEIVE A DATE AND COVERT THE DATE TO
      *    AN INTEGER IN A CALLED PROGRAM TO DETERMINE DAYS FROM
      *    CURRENT DATE.
      * TRAINING PUPOSE
